//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceExpress.FlyAsiaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlyAsiaService.IFlyAsiaWebService")]
    public interface IFlyAsiaWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyAsiaWebService/updateStatusWS", ReplyAction="http://tempuri.org/IFlyAsiaWebService/updateStatusWSResponse")]
        int updateStatusWS(string statusPO, string purOrderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyAsiaWebService/updateStatusWS", ReplyAction="http://tempuri.org/IFlyAsiaWebService/updateStatusWSResponse")]
        System.Threading.Tasks.Task<int> updateStatusWSAsync(string statusPO, string purOrderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyAsiaWebService/getAllPurchaseOrder", ReplyAction="http://tempuri.org/IFlyAsiaWebService/getAllPurchaseOrderResponse")]
        System.Data.DataSet getAllPurchaseOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlyAsiaWebService/getAllPurchaseOrder", ReplyAction="http://tempuri.org/IFlyAsiaWebService/getAllPurchaseOrderResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllPurchaseOrderAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlyAsiaWebServiceChannel : ServiceExpress.FlyAsiaService.IFlyAsiaWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlyAsiaWebServiceClient : System.ServiceModel.ClientBase<ServiceExpress.FlyAsiaService.IFlyAsiaWebService>, ServiceExpress.FlyAsiaService.IFlyAsiaWebService {
        
        public FlyAsiaWebServiceClient() {
        }
        
        public FlyAsiaWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlyAsiaWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyAsiaWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlyAsiaWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int updateStatusWS(string statusPO, string purOrderNo) {
            return base.Channel.updateStatusWS(statusPO, purOrderNo);
        }
        
        public System.Threading.Tasks.Task<int> updateStatusWSAsync(string statusPO, string purOrderNo) {
            return base.Channel.updateStatusWSAsync(statusPO, purOrderNo);
        }
        
        public System.Data.DataSet getAllPurchaseOrder() {
            return base.Channel.getAllPurchaseOrder();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllPurchaseOrderAsync() {
            return base.Channel.getAllPurchaseOrderAsync();
        }
    }
}
